name: Android Build CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Setup Java JDK 17 (Necessário para as ferramentas do SDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Switch to Java JDK 11 (Obrigatório para build Haxe/Lime antigo)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android NDK (Versão r21e estável para Haxe)
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
          local-path: ${{ github.workspace }}/android-ndk

      - name: Instalar Bibliotecas Haxe (Haxelibs)
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install flixel 4.11.0 --quiet
          haxelib install hxcpp 4.2.1 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flxanimate 3.0.4 --quiet
          haxelib install firetongue --quiet
          haxelib install flixel-ui 2.4.0 --quiet
          haxelib install flixel-addons 2.11.0 --quiet
          haxelib git extension-webview https://github.com/TeamX02/extension-webview.git --quiet

      - name: Configurar Lime para Android
        run: |
          haxelib run lime setup
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ github.workspace }}/android-ndk
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Compilar para Android (Release)
        # Este passo pode levar de 10 a 20 minutos
        run: haxelib run lime build android -release -DHXCPP_ANDROID_PLATFORM=26

      - name: Coletar e Enviar APK (Artefato)
        uses: actions/upload-artifact@v4
        with:
          name: DDTO-Android-Build
          # O asterisco duplo garante que ele encontre o APK mesmo se a estrutura de pastas variar levemente
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
